update third party content:
  stage: build
  only:
    - main
  image: bitnami/git
  script:
    - git --version
    - git config --global user.name 'Methods Hub bot'
    - git config --global user.email 'methods-hub-bot@gesis.org'
    - date > git-test.txt
    - git add -f git-test.txt
    - git commit -m '[bot] Markdown file update'
    - git checkout -b main
    - git remote set-url https://methods-hub-bot:${methods_hub_bot_token}@git.gesis.org/methods-hub/portal.git
    - git push origin main

pages:
  stage: deploy
  only:
    - main
  image: docker-private-snapshots.gesis.intra/gesis/methods-hub/quarto:latest
  script:
    - quarto check
    - quarto render -t html --output-dir public
  artifacts:
    paths:
      - public


