stages:
  - container
  - build
  - deploy

build and register methods hub docker image:
  stage: container
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      changes:
        - Dockerfile
        - env.yaml
  image: docker-private.gesis.intra/gesis/dc:5.7
  services:
    - name:  docker-private.gesis.intra/gesis/dind:5.5
      alias: docker
  script:
    - docker build --no-cache --pull -t docker-private-snapshots.gesis.intra/gesis/methods-hub/portal:latest .
    - docker push docker-private-snapshots.gesis.intra/gesis/methods-hub/portal:latest

update third party content:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_AUTHOR != "Methods Hub bot <methods-hub-bot@gesis.org>"
  allow_failure: true
  image: docker-private-snapshots.gesis.intra/gesis/methods-hub/portal:latest
  script:
    - git --version
    - git config --global user.name 'Methods Hub bot'
    - git config --global user.email 'methods-hub-bot@gesis.org'
    - git config --global --add safe.directory /builds/methods-hub/portal
    - git remote set-url origin https://methods-hub-bot:${methods_hub_bot_token}@git.gesis.org/methods-hub/portal.git
    - git checkout -f -b main
    - Rscript --verbose --vanilla demetrius.R
    - git commit -m '[bot] Markdown file update'
    - git push origin main

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_AUTHOR == "Methods Hub bot <methods-hub-bot@gesis.org>"
  image: docker-private-snapshots.gesis.intra/gesis/methods-hub/quarto:latest
  script:
    - quarto check
    - quarto render -t html --output-dir public
  artifacts:
    paths:
      - public


