stages:
  - config
  - prepare
  - build
  - test

.manual-web:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'web'
      when: manual
      allow_failure: true

Assign Docker image tag:
  stage: config
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - Dockerfile
      variables:
        DOCKER_IMAGE_TAG: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        DOCKER_IMAGE_TAG: latest
    - if:  ($CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_BRANCH == 'main')
      variables:
        DOCKER_IMAGE_TAG: latest
  script:
    - echo "DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG}" >> docker.env
  artifacts:
    reports:
      dotenv: docker.env

Build container with pkgdown:
  stage: prepare
  rules:
    - !reference [.manual-web, rules]
    - if: ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == 'main') || $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - Dockerfile
  image: docker-private.gesis.intra/gesis/dc:5.7
  services:
    - name:  docker-private.gesis.intra/gesis/dind:5.5
      alias: docker
  script:
    - docker build --target pkgdown --no-cache --pull -t docker-private-snapshots.gesis.intra/gesis/methods-hub/methodshub/pkgdown:${DOCKER_IMAGE_TAG} .
    - docker push docker-private-snapshots.gesis.intra/gesis/methods-hub/methodshub/pkgdown:${DOCKER_IMAGE_TAG}

pages:
  stage: build
  rules:
    - !reference [.manual-web, rules]
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == 'main'
      changes:
        - R/**/*
  image: docker-private-snapshots.gesis.intra/gesis/methods-hub/methodshub/pkgdown:${DOCKER_IMAGE_TAG}
  script:
    - Rscript --verbose --vanilla -e 'pkgdown::build_site()'
    - mv docs public
    - cp -r img public/img
  artifacts:
    paths:
      - public


