project:
  type: website
  render:
    - "*.md"
  resources:
    - gesis-web-frontend-framework

website:
  title: "GESIS - Methods Hub"
  site-url: https://methods-hub.gesis.org

format:
  html:
    template: _templates/gesis.html
    theme:
      - _sass/gesis.scss
      - _sass/methods_hub.scss

