stages:
  - download_contributions
  - create_containers
  - render_contributions
  - render_report
  - generate_card_files

testing:
  minimal_example: true
  debug: true
  trace_files: true # todo add this as switch to only trace files if debugging an issue
