---
title: Input Format
---

`andrew` tries to support a wide range of input formats for content.
Each piece of content is represented by a Git repository **and** a file.
In the abstence of a file, the `README.md` should be used.

# Supported formats

## `README.md`

Example: https://github.com/GESIS-Methods-Hub/minimal-example-readme

This should be used **only** as a fallback.

### Required

- [ ] Markdown file named `README.md`
- [ ] Heading level 1 in the `README.md`
- [ ] Author name in Git commit information

### Desired

- [ ] Image (900×600 pixels) named `cover.jpg` or `cover.svg` to use as cover

## (Pandoc) Markdown

Example: https://github.com/GESIS-Methods-Hub/minimal-example-md

This is an expansion of John Gruber's [Markdown](https://daringfireball.net/projects/markdown/) syntax that supports tables, citation, ...

### Required

- [ ] Markdown file named `index.md` or another name except `README.md`
- [ ] YAML header block at the begin of the Markdown file defining

      - `title`
      - `author`

### Desired

- [ ] Complete author details, including affiliation
- [ ] Image (900×600 pixels) to use as cover and associated metadata in the YAML header block at the begin of the Markdown file defining

      - `image`
      - `image-alt`

## Quarto (document)

Example: https://github.com/GESIS-Methods-Hub/minimal-example-qmd-rstats-units

Quarto is based on Pandoc Markdown and adds support to executable code blocks.

### Required

- [ ] Markdown file named `index.qmd` or another name except `README.qmd`
- [ ] YAML header block at the begin of the Markdown file defining

      - `title`
      - `author`
- [ ] Configuration files for `repo2docker` to use when installing dependencies

### Desired

- [ ] Complete author details, including affiliation
- [ ] Image (900×600 pixels) to use as cover and associated metadata in the YAML header block at the begin of the Markdown file defining

      - `image`
      - `image-alt`

## Jupyter Notebook (using Quarto extension)

Example: https://github.com/GESIS-Methods-Hub/minimal-example-ipynb-python

Markdown cells in the Jupyter Notebook **must** use Quarto Markdown instead of [Jupyter Notebook Markdown](https://jupyterbook.org/en/stable/file-types/markdown.html) (based on [CommonMark Markdown](https://commonmark.org/)) and [MyST Markdown](https://mystmd.org/).

### Required

- [ ] Markdown file named `index.ipynb` or another name except `README.ipynb`
- [ ] YAML header block in the first cell of the Jupyter Notebook defining

      - `title`
      - `author`

      The cell **must be** of type `raw`.
- [ ] Configuration files for `repo2docker` to use when installing dependencies

### Desired

- [ ] Complete author details, including affiliation
- [ ] Image (900×600 pixels) to use as cover and associated metadata in the YAML header block in the first cell of the Jupyter Notebook defining

      - `image`
      - `image-alt`

      The cell **must be** of type `raw`.

## Python Package

See [`README.md` section](#readm-me).

## R Package

See [`README.md` section](#readm-me).

## R Package (with `pkgdown` website)

Example: https://github.com/GESIS-Methods-Hub/minimal-example-rstats-package

### Required

- [ ] `DESCRIPTION` file with metadata of the R package
- [ ] R Markdown file named `vignettes/*.Rmd` or another name except `README.md`
- [ ] YAML header block at the begin of the Markdown file defining

      - `title`
      - `author`
- [ ] Additional configuration files for `repo2docker` to use when installing dependencies

### Desired

- [ ] Complete author details, including affiliation
- [ ] Image (900×600 pixels) to use as cover and associated metadata in the YAML header block at the begin of the Markdown file defining

      - `image`
      - `image-alt`

## R Shiny App

Example: https://github.com/GESIS-Methods-Hub/minimal-example-shiny-rstats

### Required

- [ ] `app.R` file with the logic of the R Shiny app
- [ ] Markdown file named `index.md` or another name except `README.md`
- [ ] YAML header block at the begin of the Markdown file defining

      - `title`
      - `author`
- [ ] Configuration files for `repo2docker` to use when installing dependencies

### Desired

- [ ] Complete author details, including affiliation
- [ ] Image (900×600 pixels) to use as cover and associated metadata in the YAML header block at the begin of the Markdown file defining

      - `image`
      - `image-alt`

## Microsoft Office Word 2007 (DOCX) - Guide

Example: https://github.com/GESIS-Methods-Hub/minimal-guide-example-docx

### Required

- [ ] Microsoft Office Word 2007 file named `index.md` or another name
- [ ] Title using [style](https://support.microsoft.com/en-us/office/apply-styles-f8b96097-4d25-4fac-8200-6139c8093109) `Title`
- [ ] One author name per paragrah using the [style](https://support.microsoft.com/en-us/office/apply-styles-f8b96097-4d25-4fac-8200-6139c8093109 `Author`.

### Desired

- [ ] Image named `cover.jpg` or `cover.svg` to use as cover

## Microsoft Office Word 2007 (DOCX) - Interview

Example: https://github.com/GESIS-Methods-Hub/minimal-interview-example-docx

### Required

- [ ] Microsoft Office Word 2007 file named `index.md` or another name
- [ ] Title using [style](https://support.microsoft.com/en-us/office/apply-styles-f8b96097-4d25-4fac-8200-6139c8093109 `Title`
- [ ] One author name per paragrah using the [style](https://support.microsoft.com/en-us/office/apply-styles-f8b96097-4d25-4fac-8200-6139c8093109 `Author`.

### Desired

- [ ] Image (900×600 pixels) named `cover.jpg` or `cover.svg` to use as cover

# Unsupported formats (yet)

## Quarto (book)

**Not supported yet**. Visit https://github.com/GESIS-Methods-Hub/andrew/issues/119 for updates.

## Markedly Structured Text (MyST)

**Not supported yet**. Visit https://github.com/GESIS-Methods-Hub/andrew/issues/59 for updates.

Example: https://github.com/GESIS-Methods-Hub/minimal-example-myst

## Jupyter Notebook (using MyST extension)

**Not supported yet**. Visit https://github.com/GESIS-Methods-Hub/andrew/issues/59 for updates.

Example: https://github.com/GESIS-Methods-Hub/minimal-example-ipynb-myst-python

## Jupyter book

**Not supported yet**. Visit https://github.com/GESIS-Methods-Hub/andrew/issues/120 for updates.

## Python Package (with Sphinx website)

**Not supported yet**. Visit https://github.com/GESIS-Methods-Hub/andrew/issues/121 for updates.
