project:
  type: website
  render:
    - "*.md"

website:
  title: "MethodsHub"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    template-partials:
      - _partials/title-block.html
    theme: cosmo
