project:
  type: website
  render:
    - "*.md"
  resources:
    - img

website:
  title: "GESIS - KODAQS Toolbox"
  navbar:
    # logo: "img/logo_gesis.svg"
    # background: "#ADD8E6"
    pinned: true
    title: false
    favicon: img/favicon.ico
    background: light
    foreground: dark
    logo: img/logo_gesis_en.png #img/toolbox_logo.png
    left:
      - href: index.md
        text: Home
      # - href: contributions.md
      #   text: Contribution
      # - href: handson.md
      #   text: HandsOn
      - href: https://www.gesis.org/forschung/drittmittelprojekte/projektseite-kodaqs
        text: About
      - href: license.md
        text: License
    right:
      - href: topics.md
        text: Topics
  page-footer:
    left: |
      **Standort Mannheim**  
      GESIS - Leibniz-Institut für Sozialwissenschaften  
      B6, 4-5  
      68159 Mannheim  
      Telefon: +49-(0)621-1246-0  
      Fax: +49-(0)621-1246-100
    center: |
      **Standort Köln**  
      GESIS - Leibniz-Institut für Sozialwissenschaften  
      Unter Sachsenhausen 6-8  
      50667 Köln  
      Telefon: +49-(0)221-47694-0  
      Fax: +49-(0)221-47694-199

    right: |
      ![GESIS ist ein Institut der Leibniz-Gemeinschaft](https://www.gesis.org/typo3conf/ext/gesis_web_ext/Resources/Public/webpack/dist/img/leibniz_logo_de_white.svg)  
      [Impressum](https://www.gesis.org/institut/impressum) [Datenschutz](https://www.gesis.org/institut/datenschutz)

format:
  html:
    template-partials:
      - _partials/title-block.html
      - _partials/shiny-title-block.html
      - _partials/method-title-block.html
      - _partials/guide-title-block.html
    theme: [gesis-theme.scss,cerulean]
    css: styles.css
    fontsize: 1rem
    linestretch: 1.6
    # title-block-banner: img/logos/microsite.png
    # title-block-banner-color: '#fff'
    anchor-sections: false
    smooth-scrolling: false
    toc: true
    toc-title: " "
    comments:
      giscus:
        repo: GESIS-Methods-Hub/andrew
    # include-after-body: _partials/kodaqs_footer.html