project:
  type: website
  render:
    - "*.md"
  resources:
    - img

website:
  title: "KODAQS Toolbox"
  navbar:
    # logo: "img/logo_gesis.svg"
    logo: img/toolbox_logo.png
    left:
      - href: index.md
        text: Home
      - href: contributions.md
        text: Contribution
      - href: topics.md
        text: Topics
  body-footer: "Aggregated by [`andrew`](https://github.com/GESIS-Methods-Hub/andrew) and render by [Quarto](https://quarto.org/)"
  page-footer:
    left: "<div style=\"flex: 1; text-align: left; color: white; font-size: 16px; padding-left: 20%; padding-right: 20%;\"><strong>Standort Mannheim</strong><br>GESIS - Leibniz-Institut für Sozialwissenschaften<br>B6, 4-5<br>68159 Mannheim<br>Telefon: +49-(0)621-1246-0<br>Fax: +49-(0)621-1246-100</div>"
    center: "<div style=\"flex: 1; text-align: left; color: white; font-size: 16px;\"><strong>Standort Köln</strong><br>GESIS - Leibniz-Institut für Sozialwissenschaften<br>Unter Sachsenhausen 6-8<br>50667 Köln<br>Telefon: +49-(0)221-47694-0<br>Fax: +49-(0)221-47694-199</div>"
    right: "<div style=\"flex: 1; text-align: center; color: white; font-size: 16px;\"><a href=\"https://www.facebook.com\" style=\"margin-right: 10px;\"><img src=\"/img/facebook.jpeg\" alt=\"Facebook\" style=\"width: 20px;\"></a><a href=\"https://www.x.com\" style=\"margin-right: 10px;\"><img src=\"/img/twitter_logo.jpeg\" alt=\"Twitter\" style=\"width: 20px;\"></a><a href=\"https://www.linkedin.com\"><img src=\"/img/linked_in.jpeg\" alt=\"LinkedIn\" style=\"width: 20px;\"></a><br><br><img src=\"/img/leibnitz_logo_de_white.svg\" alt=\"Leibniz Gemeinschaft\" style=\"width: 100px;\"><br><a href=\"https://www.gesis.org/institut/impressum\" style=\"color: white; margin-right: 10px;\">Impressum</a><a href=\"https://www.gesis.org/institut/datenschutz\" style=\"color: white;\">Datenschutz</a></div>"
    background: "#003c78"


format:
  html:
    template-partials:
      - _partials/title-block.html
      - _partials/shiny-title-block.html
      - _partials/method-title-block.html
      - _partials/guide-title-block.html
    theme: cerulean
    css: styles.css
    comments:
      giscus:
        repo: GESIS-Methods-Hub/andrew
