project:
  type: website
  render:
    - "*.md"
  resources:
    - img

website:
  title: "KODAQS Toolbox"
  navbar:
    # logo: "img/logo_gesis.svg"
    logo: img/toolbox_logo.png
    left:
      - href: index.md
        text: Home
  body-footer: "Aggregated by [`andrew`](https://github.com/GESIS-Methods-Hub/andrew) and render by [Quarto](https://quarto.org/)"
  page-footer: "![](img/gesis_footer.jpeg)"

format:
  html:
    template-partials:
      - _partials/title-block.html
      - _partials/shiny-title-block.html
      - _partials/method-title-block.html
      - _partials/guide-title-block.html
    theme: cerulean
    css: styles.css
    comments:
      giscus:
        repo: GESIS-Methods-Hub/andrew
