project:
  type: website
  render:
    - "*.md"
  resources:
    - img

website:
  title: "Demo of MethodsHub"
  navbar:
    left:
      - href: index.md
        text: Home

format:
  html:
    template-partials:
      - _partials/title-block.html
    theme: cosmo
    comments:
      giscus: 
        repo: GESIS-Methods-Hub/methodshub
